FROM ubuntu:14.04

MAINTAINER Eric Ogren <eogren@gmail.com>

# Add core
RUN apt-get update ## Last updated 1/4/2015
RUN apt-get -y upgrade 
RUN apt-get install -y software-properties-common python-software-properties
