global
        chroot /var/lib/haproxy
        user haproxy
        group haproxy
        maxconn 4096

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        contimeout 5000
        clitimeout 50000
        srvtimeout 50000
        retries 3
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

#listen frontend 0.0.0.0:80
#        mode http
#        stats enable
#        stats uri /haproxy?stats
#        stats realm Sekret
#        stats auth eogren:password
#        balance leastconn
#        option http-server-close
#        timeout http-keep-alive 2000
#        option forwardfor
#        option httpchk /health
#
#        server foo1 localhost:8005 check port 8006

listen service 0.0.0.0:8080
        mode http
        stats enable
        stats uri /haproxy?stats
        stats realm Sekret
        stats auth eogren:password
        balance leastconn
        option http-server-close
        timeout http-keep-alive 2000
        option forwardfor
        option httpchk /health

	server foo1 localhost:8005 check port 8006
